export const routesConfig = [
  // AUTH
  {
    method: "POST",
    path: "/register",
    module: "auth",
    action: "auth.register",
    summary: "Register user",
    body: "Register",
    auth: false,
  },
  {
    method: "POST",
    path: "/login",
    module: "auth",
    action: "auth.login",
    summary: "Login user",
    body: "Login",
    auth: false,
  },
  {
    method: "POST",
    path: "/refresh",
    module: "auth",
    action: "auth.refreshToken",
    summary: "Refresh access token",
    body: "RefreshToken",
    auth: false,
  },
  {
    method: "POST",
    path: "/logout",
    module: "auth",
    action: "auth.logout",
    summary: "Logout user",
    auth: true,
  },
  {
    method: "POST",
    path: "/forgot-password",
    module: "auth",
    action: "auth.forgotPassword",
    summary: "Request password reset",
    body: "ForgotPassword",
    auth: false,
  },
  {
    method: "POST",
    path: "/reset-password",
    module: "auth",
    action: "auth.resetPassword",
    summary: "Reset password",
    body: "ResetPassword",
    auth: false,
  },

  // PRODUCTS
  {
    method: "GET",
    path: "/",
    module: "products",
    action: "product.list",
    summary: "List products",
    auth: true,
  },
  {
    method: "POST",
    path: "/",
    module: "products",
    action: "product.create",
    summary: "Create product",
    body: "Product",
    auth: true,
  },
  {
    method: "PUT",
    path: "/:id",
    module: "products",
    action: "product.update",
    summary: "Update product",
    body: "Product",
    auth: true,
  },
  {
    method: "DELETE",
    path: "/:id",
    module: "products",
    action: "product.remove",
    summary: "Remove product",
    auth: true,
  }
];
